#pragma once
#include <string>
#include <map>
#include "msgDefine.h"
//#include "common.h"
using namespace std;
#define LISTEN_PROTO   "tcp"
#define LISTEN_ADDR_LEN 60
#define IDENTITY_STR_LEN 100

#define FRONTEND_MSG (WM_USER + 1)
#define CLIENTWORKER_MSG (WM_USER + 2)
#define JAVAWORKER_MSG (WM_USER + 3)
#define FACEDETECTWORK_MSG (WM_USER + 4)
#define FACETELLWORK_MSG (WM_USER + 5)
#define CLIENT_CONNECTTEST (WM_USER + 6)
#define SERVER_GET_PC_CLIENT_VERSION (WM_USER + 7)
#define PC_CONFIRM_USERNAME_AND_PWD (WM_USER + 8)
#define JAVA_SEND_USERNAME_NOT_EXIST (WM_USER + 9)					
#define SERVER_GETCAMERA_INFO	(WM_USER + 10)
#define JAVA_SEND_CAMERA_INFO (WM_USER + 11)
#define FACEDETECT_NEED_FACETELL (WM_USER + 12)
#define FACE_NEED_TELL (WM_USER + 13)
#define FACE_TELL_RESULT (WM_USER + 14)
#define JAVA_SEND_PASSWORD_ERROR (WM_USER + 15)
#define JAVA_SEND_OK (WM_USER + 16)
#define CLIENT_GET_CAMERA_INFO (WM_USER + 16)
#define CAMERA_INFO_UPDATE (WM_USER + 17)
#define FACEDETECTION_ONEPICTURE (WM_USER + 18)
#define FACEIDF_FACEFEATURES_IN (WM_USER + 19)
#define FACEIDF_FACEFEATURES_OUT (WM_USER + 20)
#define FACEDETECTION_PICTUREDIR_IN (WM_USER + 21) 
#define TRACKSERVER_PERSON_LOST (WM_USER + 22)
#define TRACESERVER_PERSON_RETELL (WM_USER + 23)
#define TRACESERVER_PERSON_INTRACKING (WM_USER + 24)
#define TRACESERVER_MAKESUER_TARGET (WM_USER + 25)
#define TRACESERVER_GOTOANOTHER_CAMERA (WM_USER + 26)
#define TRACESERVER_REQUEST_TRACKSERVER_IP (WM_USER + 27)
#define JAVATHREAD_PUSH_TRACK_INITMSG (WM_USER + 28)
#define FACETELL_ALIVE_CHECK (WM_USER + 29)
#define FACETELL_RETURN_IAM_ALIVE (WM_USER + 30)
#define SHAPE_MSG2_TRACK (WM_USER + 31)
#define TRACK_ALIVE_CHECK (WM_USER + 32)
#define TRACK_RETURN_IAM_ALIVE (WM_USER + 33)
#define BROADCAST_ALIVE_CHECK (WM_USER + 34)
#define BROADCAST_RETURN_IAM_ALIVE (WM_USER + 35)
#define CLIENT_SEARCH_CAPTURE_LOOK_BACK (WM_USER + 36)
#define JAVA_RETURN_CAPTURE_LOOK_RESULT (WM_USER + 37)
#define CLIENT_SEARCH_ALARAM_LOOK_BACK (WM_USER + 38)
#define JAVA_RETURN_ALARAM_LOOK_BACK (WM_USER + 39)
#define CLIENT_SEARCH_ALARAM_DETAIL (WM_USER + 40)
#define JAVA_RETURN_ALARAM_DETAIL (WM_USER + 41)
#define CLIENT_SEARCH_RECORD_LOOK_BACK (WM_USER + 42)
#define JAVA_RETURN_RECORD_LOOK_BACK (WM_USER + 43)
#define CLIENT_LOG_RECORD (WM_USER + 44)
#define JAVA_LOG_REDORD_RETURN (WM_USER + 45)
#define CLIENT_TRACK_PERSON_DETAIL (WM_USER + 46)
#define CLIENT_ALARM_DEAL (WM_USER + 47)
#define SHAPE_PERSON_RETELL_REC2_TRACK (WM_USER + 48) 
#define CAMERA_STATUS_CHECK (WM_USER + 49)
#define RTSP_CAMERA_STATUS_REPLY (WM_USER + 50)
#define SERVER_STATUS_PUSH (WM_USER + 51)
#define SERVER_TRANS_JAVAREQ_CHANGE_FACELIB (WM_USER + 52)
#define FACETH_REPLY2_JAVAREQ_CHANGE_FACELIB (WM_USER + 53)
#define JAVA_CHANGE_CAMERA (WM_USER + 54)
#define RTSP_NEED_FACEDT (WM_USER + 55)
#define RTSP_CHANGE_FACEDETECTION_CAMERA (WM_USER + 56)
#define FACETELL_CHANGE_CAMERA_STATEG (WM_USER + 57)
#define TRACK_CHANGE_FACEDETECTION_CAMERA (WM_USER + 58)
#define FACEDT_CONNECT_REPLY (WM_USER + 59)
#define FACE_TELL_CONNECT_REPLY (WM_USER + 60)
#define RTSP_CONNECT_REPLY (WM_USER + 61)
#define JAVA_CHANGE_STATEG (WM_USER + 62)
#define FACEDT_CHANGE_FACEDETECTION_CAMERA (WM_USER + 63)

/*CUIJIANHUA+ADD+CODE*/ /*转发来自java的相机布控策略修改消息给人脸检测*/
#define TRAN_CHANGE_STATEG_MSG_TO_FACE_DT (WM_USER + 63)
#define RTSP_CHANGE_STATEG (WM_USER + 64)
#define FACEDT_CHANGE_STATEG (WM_USER + 65)
#define TRACK_CHANGE_CAMERA_STATEG (WM_USER + 66)
#define FACEDT_ALIVE_CHECK (WM_USER + 67)
#define FACEDT_RETURN_IAM_ALIVE (WM_USER + 68)
#define CLIENT_GET_FACE_CHECKIN (WM_USER + 69)
#define FACEDT_GET_FACE_CHECKIN (WM_USER + 70)
#define FACETELL_GET_FACE_CHECKIN (WM_USER + 71)
#define FACEDT_FACE_CHECKIN_FAILED (WM_USER + 72)
#define CLIENT_USING_IMG_CHECKIN_IMG (WM_USER + 73)
#define FACEDT_GET_USING_IMG_CHECKIN_IMG_FAILED (WM_USER + 74)
#define FACEDT_GET_USING_IMG_CHECKIN_IMG_SUCCESS (WM_USER + 75)
#define FACETELL_RETURN_PIC_SEARCH_RESULT (WM_USER + 76)
#define FACETELL_SEARCH_PIC_FAILED (WM_USER + 77)

#define PIC_SEARCH_RESULT2_JAVA (WM_USER + 78)
#define JAVA_RETURN_PIC_SEARCH_RESULT (WM_USER + 79)
#define PIC_SEARCH_SEARCH_PIC_FAILED (WM_USER + 80)

#define RTSP_CHANGE_CAMERA (WM_USER + 81)
#define JAVA_ALIVE_CHECK (WM_USER + 82)
#define JAVA_RETURN_IAM_ALIVE (WM_USER + 83)
#define CLIENT_ALIVE_CHECK (WM_USER + 84)
#define CLIENT_RETURN_IAM_ALIVE (WM_USER + 85)
#define CLIENT_FACE_SEARCH (WM_USER + 86)
#define FACEDT_FACE_SEARCH_FAILED (WM_USER + 87)
#define FACEDT_FACE_SEARCH_SUCCESS (WM_USER + 88)
#define FACETELL_RETURN_FACE_SEARCH_RESULT (WM_USER + 89)
#define FACETELL_RESULT2_DATA_UPATE (WM_USER + 90)
#define CLIENT_UPDATE_ALARM_SET (WM_USER + 91)
#define RTSP_ALARM_VIDEO_SAVE (WM_USER + 92)
extern int nListJava;
extern int nListJavaInit;
extern int nReqJava;
extern int nFaceTell;
extern int nFaceTrackPort;
extern int nShapePort;
extern int nSearchPort;
extern int nPicDataUpate;
extern int nRtspServer;
extern string strFaceDetectUrl;
extern string strFacePointInfoUrl;
extern string strMsgHeadFile;
extern int FaceTellPort;
extern string strFaceTellUrl;
extern double nSimilarity;
extern char strFaceDetect[LISTEN_ADDR_LEN];
extern char strFaceTell[LISTEN_ADDR_LEN];
extern char strRtspSever[LISTEN_ADDR_LEN];
extern char strTrack[LISTEN_ADDR_LEN];
extern char strShape[LISTEN_ADDR_LEN];
extern char strSearchPic[LISTEN_ADDR_LEN];
extern char strTrackInit[LISTEN_ADDR_LEN];
extern char strDataUpdate[LISTEN_ADDR_LEN];
enum _FaceDetectStrategy
{
	FACEDETECT_JUST_REPLY = 0,//ÈËÁ³¼ì²â½ö½ö»Ø¸´
	FACEDETECT_NEED_TELL = 1,//ÈËÁ³¼ì²âÐèÒªÊ¶±ð	
};
extern int nFaceDetectStrategy;//Ä¬ÈÏÐèÒªÈËÁ³Ê¶±ð
extern map<int, int> rtsp2java;
extern map<int, int> func2java;
bool msg_code_map_init();
extern int change_camera_timeout;
extern std::string  g_envalue_file;